### ISSUE TITLE
fedora 36

### ISSUE THREAD

**Issue by LennyPenny** [hlovdal/nebula-overlay-networking#1]
would be cool to get a fedora 36 version of this!

**Comment by hlovdal** [comment]
[Fedora 36](https://copr.fedorainfracloud.org/coprs/hlovdal/nebula-overlay-networking/repo/fedora-36/hlovdal-nebula-overlay-networking-fedora-36.repo) (and [rawhide](https://copr.fedorainfracloud.org/coprs/hlovdal/nebula-overlay-networking/repo/fedora-rawhide/hlovdal-nebula-overlay-networking-fedora-rawhide.repo)) added and [built](https://copr.fedorainfracloud.org/coprs/hlovdal/nebula-overlay-networking/build/4414951/).
